"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](surface0)\
$os\
$username\
[](bg:blue fg:surface0)\
$directory\
[](fg:blue bg:yellow)\
$git_branch\
$git_status\
[](fg:yellow bg:overlay2)\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:overlay2 bg:surface0)\
$docker_context\
$conda\
[](fg:surface0 bg:base)\
$time\
[ ](fg:base)\
$line_break$character"""

palette = 'catppuccin_mocha'



[os]
disabled = false
style = "bg:surface0 fg:text"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
EndeavourOS = ""
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[username]
show_always = true
style_user = "bg:surface0 fg:text"
style_root = "bg:surface0 fg:text"
format = '[ $user ]($style)'

[directory]
style = "fg:base bg:blue"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:teal"
format = '[[ $symbol $branch ](fg:base bg:yellow)]($style)'

[git_status]
style = "bg:yellow"
format = '[[($all_status$ahead_behind )](fg:base bg:yellow)]($style)'

[nodejs]
symbol = ""
style = "bg:overlay2"
format = '[[ $symbol( $version) ](fg:base bg:overlay2)]($style)'

[c]
symbol = " "
style = "bg:overlay2"
format = '[[ $symbol( $version) ](fg:base bg:overlay2)]($style)'

[rust]
symbol = ""
style = "bg:overlay2"
format = '[[ $symbol( $version) ](fg:base bg:overlay2)]($style)'

[golang]
symbol = ""
style = "bg:overlay2"
format = '[[ $symbol( $version) ](fg:base bg:overlay2)]($style)'

[php]
symbol = ""
style = "bg:overlay2"
format = '[[ $symbol( $version) ](fg:base bg:overlay2)]($style)'

[java]
symbol = " "
style = "bg:overlay2"
format = '[[ $symbol( $version) ](fg:base bg:overlay2)]($style)'

[kotlin]
symbol = ""
style = "bg:overlay2"
format = '[[ $symbol( $version) ](fg:base bg:overlay2)]($style)'

[haskell]
symbol = ""
style = "bg:overlay2"
format = '[[ $symbol( $version) ](fg:base bg:overlay2)]($style)'

[python]
symbol = ""
style = "bg:overlay2"
format = '[[ $symbol( $version) ](fg:base bg:overlay2)]($style)'

[docker_context]
symbol = ""
style = "bg:surface0"
format = '[[ $symbol( $context) ](fg:#83a598 bg:surface0)]($style)'

[conda]
style = "bg:surface0"
format = '[[ $symbol( $environment) ](fg:#83a598 bg:surface0)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:base"
format = '[[  $time ](fg:text bg:base)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:green)'
error_symbol = '[](bold fg:red)'
vimcmd_symbol = '[](bold fg:surface0)'
vimcmd_replace_one_symbol = '[](bold fg:surface0)'
vimcmd_replace_symbol = '[](bold fg:surface0)'
vimcmd_visual_symbol = '[](bold fg:green)'


[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
